### ISSUE TITLE
"Cannot read property get of undefined" errors

### ISSUE THREAD

**Issue by jayporta** [AurityLab/vue-recaptcha-v3#391]
At work we're seeing thousands of errors reported through Sentry that say "Cannot read property get of undefined"

Environment

OS name and version: Windows and Mac

google/recaptcha version: Latest as served by https://www.recaptcha.net/recaptcha/api.js

Here's a sample of browser occurances:
56.70% | Chrome 89.0.4389
14.43% | Chrome 75.0.3770
7.22% | Chrome 86.0.4240
6.19% | Sogou Explorer 1.0
3.09% | Chrome 78.0.3904
3.09% | Chrome 88.0.4324
3.09% | Chrome 81.0.4044
2.06% | Chrome 85.0.4183
1.03% | Chrome 79.0.3945
1.03% | Chrome 91.0.4442
1.03% | Chrome 80.0.3987
1.03% | Chrome 87.0.4280

All of the error messages are like the following, but sometimes it's k.get, j.get, etc.

TypeError: Cannot read property 'get' of undefined
arguments: [{"message":"Cannot read property 'get' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'get' of undefined\n at Array. (https://www.gstatic.com/recaptcha/releases/bfvuz6tShG5aoZp4K4zPVf5t/recaptcha__zh_tw.js:106:312)\n at https://www.gstatic.com/recaptcha/releases/bfvuz6tShG5aoZp4K4zPVf5t/recaptcha__zh_tw.js:215:83\n at t.

"TypeError: Cannot read property 'get' of undefined\n    at Array.<anonymous> (https://www.gstatic.com/recaptcha/releases/bfvuz6tShG5aoZp4K4zPVf5t/recaptcha__en.js:43:44)\n    at https://www.gstatic.com/recaptcha/releases/bfvuz6tShG5aoZp4K4zPVf5t/recaptcha__en.js:310:384\n    at t.<anonymous>

Sometimes I just see: TypeError: J is undefined

**Comment by WipeAir** [comment]
Is there an example on how to reproduce this issue? 
Actually I think it's an error from recaptcha itself rather than from this plugin...

**Comment by jayporta** [comment]
I no longer work for the company where we saw these issues. I also think it's a recaptcha issue, not the plugin, but I wanted to notify you anyway in case maybe there's some connection or if there's something that can be done on vue-recaptcha-v3's end.

I can't access the old code from my previous employer, but I remember we added the plugin to the Vue instance from main.js, and then from App.vue grabbed the token after waiting for recaptchaLoaded. Very similar to the usage instructions.

I also reported this on Google's repo [issue thread](https://github.com/google/recaptcha/issues/449). Someone else responded that they've run into the same issue.
